### PR TITLE
File 263

### PR DESCRIPTION
**Pull request by JTY009**
Updated README which now has in addition test-only and admin app related endpoints.

### CODE REVIEW

**Comment by kings13y** [comment]
Tbh, that had been my first thoughts too @hannesstockner . Mine were actually, that we should document them, but suspected we leave it out of the readme. I believe Dominic was keen for it all to go in the readme, and (after thinking about it more), I'm OK with that, so long as we clearly mark INTERNAL endpoints as such. Maybe **BOLD BLOCK CAPS** too!

**Comment by hannesstockner** [comment]
I think the readme should include and focus on all endpoints external end users can use. It should give them a clear overview of how they can interact with our service. Adding internal and test only endpoints to it adds confusion and questions and encourages end users to try them out. Additionally it adds some overhead on maintaining the readme and keeping it up to date when modifying/adding/deleting some of the internal endpoints. I would strongly advice against it and try to add documentation for them in a different way (ie javadoc) if needed.

**Comment by kings13y** [comment]
So.. I'm sorta OK with these being in the readme _for now_.. Feels like a broader chat is worth having around API documentation later on (post 2.5 upgrade I suggest), where we can re-evaluate and see what options we have. Personally I prefer swagger or the like for API docs (maybe a tab on the admin app that captures the admin and test endpoints..). But **for now**, happy to just have to captured _somewhere_ tbh. @JTY009 can you add the something at the top of the readme that TEST and Admin endpoints should not be used by service clients and the documentation is just provided caveat emptor pls.

**Comment by JTY009** [comment]
I can add a disclaimer of some sorts at the top.

**Pull request closed without merging**
